### ISSUE TITLE
0.8.1 seems to be broken on crates.io

### ISSUE THREAD

**Issue by sowbug** [urholaukkarinen/egui-toast#14]
I am not sure whether 0.8.1 is meant to depend on egui 0.23.0, but there seems to be a disagreement between crates.io and the repository. crates.io thinks it depends on 0.22, which breaks any project that has updated to egui 0.23.0, but the repo suggests that 0.8.1 depends on 0.23.0.

**Comment by urholaukkarinen** [comment]
egui dependency was updated to 0.23, but new egui-toast version was not published.
0.9.0 is now available in crates.io.
