### ISSUE TITLE
this run on Exclusive Full Screen?

### ISSUE THREAD

**Issue by muhammadshehbazkhanani** [urholaukkarinen/egui-toast#15]
Will this egui toast run in an exclusive full-screen overlay at the top? like league of legends, DOTA 2 e.t.c

**Comment by urholaukkarinen** [comment]
That depends on the program you are using egui-toast for. This library, or egui for that matter, does not care how things are rendered to the screen. That's the job of the egui backend, for example [egui_glow](https://github.com/emilk/egui/tree/master/crates/egui_glow).

Generally speaking, if you are drawing things in a separate window, it cannot be used as an overlay for apps that run in exclusive fullscreen mode, even if the window is configured to stay 'always-on-top'.
