### ISSUE TITLE
Semver breakage with `0.10.2`

### ISSUE THREAD

**Issue by Zenithsiz** [urholaukkarinen/egui-toast#20]
Since version `0.10.1` depends on `egui = "^0.24.1"`, using `egui = "^0.25"` is a semver breaking change, but was published as a non-breaking change in `0.10.2`.

As an example of breakage, https://github.com/alegnani/verifactory no longer compiles since it uses `egui = 0.24.1` and `egui-toast = "0.10.1"`, which allows version `0.10.2` to be selected. This results in two different `emath`s being compiled:

- emath@0.24.1
- emath@0.25.0

This then breaks when passing an `emath::align::Align2` (from `0.24.1`) to `egui_toast::Toasts::anchor` (which requires the `0.25.0` type):

```rust
error[E0308]: mismatched types
   --> src/gui/app.rs:180:21
    |
180 |             .anchor(Align2::RIGHT_TOP, (-10.0, 10.0))
    |              ------ ^^^^^^^^^^^^^^^^^ expected `emath::align::Align2`, found `Align2`
    |              |
    |              arguments to this method are incorrect
    |
    = note: `Align2` and `emath::align::Align2` have similar names, but are actually distinct types
```

**Comment by urholaukkarinen** [comment]
My bad. `0.10.2` is now yanked and `0.11.0` is published to crates.io.
