### ISSUE TITLE
Feature: Custom icons/Unicode characters without resorting to fully custom frame

### ISSUE THREAD

**Issue by metasim** [urholaukkarinen/egui-toast#25]
Great library! Thanks for sharing it!

Obviously not essential, but wanted to note it would be nice if we could somehow override this mapping in `Toasts::default_toast_contents` without resorting to a fully custom toast rendering: 

```rust
let (icon, color) = match toast.kind {
    ToastKind::Warning => ("⚠", WARNING_COLOR),
    ToastKind::Error => ("❗", ERROR_COLOR),
    ToastKind::Success => ("✔", SUCCESS_COLOR),
    _ => ("ℹ", INFO_COLOR),
};
```

**Comment by urholaukkarinen** [comment]
Thanks for the issue! Toasts now have a `ToastStyle` that can be used to customize the icons and the close button text without having to use a fully custom toast.
